'use strict';
const KEY='inverno-fit-v2';
const fresh=()=>({version:2,week:1,day:Math.min((new Date().getDay()+6)%7,5),sessions:{},diary:[],shop:{},start:''});
let state=fresh(), storageOK=true, view='allenamento';
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(validState(parsed))state=parsed;else storageOK=false;}}catch{storageOK=false;}
function validState(s){return s&&s.version===2&&Number.isInteger(s.week)&&s.week>=1&&s.week<=12&&Number.isInteger(s.day)&&s.day>=0&&s.day<6&&s.sessions&&typeof s.sessions==='object'&&!Array.isArray(s.sessions)&&s.shop&&typeof s.shop==='object'&&!Array.isArray(s.shop)&&Array.isArray(s.diary)&&s.diary.every(x=>x&&typeof x.id==='string'&&typeof x.date==='string'&&typeof x.notes==='string'&&Number.isFinite(x.week)&&[x.weight,x.waist,x.chest].every(n=>n===''||Number.isFinite(n)))&&Object.values(s.sessions).every(x=>x&&typeof x==='object'&&x.items&&typeof x.items==='object'&&Object.values(x.items).every(i=>i&&typeof i==='object'&&typeof i.done==='boolean'&&typeof i.kg==='string'&&typeof i.reps==='string'));}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
let noticeTimeout;
function notify(text){$('#message').textContent=text;$('#message').classList.add('visible');clearTimeout(noticeTimeout);noticeTimeout=setTimeout(()=>$('#message').classList.remove('visible'),4500);}
function save(){if(!storageOK){notify('Salvataggio non disponibile. Esporta i dati prima di chiudere.');return false;}try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{storageOK=false;notify('Memoria non disponibile: esporta i dati prima di chiudere.');return false;}}
function session(w=state.week,d=state.day){return state.sessions[w+'-'+d]||{items:{},completed:false,rounds:0};}
function mutableSession(){const k=state.week+'-'+state.day;return state.sessions[k]||(state.sessions[k]={items:{},completed:false,rounds:0});}
function item(id){return session().items[id]||{done:false,kg:'',reps:''};}
function previous(id){for(let w=state.week-1;w>0;w--){const x=session(w).items[id];if(x&&(x.kg||x.reps))return 'Settimana '+w+': '+(x.kg?x.kg+' kg · ':'')+(x.reps||'ripetizioni non annotate');}return 'Nessuna registrazione precedente.';}
function phase(){return PHASES[Math.floor((state.week-1)/4)];}
function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function completed(w){return DAYS.slice(0,5).filter((_,d)=>session(w,d).completed).length;}
function weekSelector(){return '<label class="week-label">Settimana <select id="week">'+Array.from({length:12},(_,i)=>'<option value="'+(i+1)+'" '+(state.week===i+1?'selected':'')+'>'+(i+1)+' / 12</option>').join('')+'</select></label>';}
function card(e,i,prefix){const id=prefix+i,x=item(id);return `<article class="card ${x.done?'done':''}" data-card="${id}"><div class="exercise-head"><span class="number">${String(i+1).padStart(2,'0')}</span><div class="text"><h3>${esc(e[0])}</h3><span class="dose">${esc(e[1])}</span></div><label class="check"><input type="checkbox" data-check="${id}" ${x.done?'checked':''} aria-label="Completato: ${esc(e[0])}"><span>Fatto</span></label></div><details><summary>Tecnica e registro</summary><p>${esc(e[2])}</p><div class="fields"><label>Peso (kg)<input type="number" inputmode="decimal" min="0" max="999" step="0.25" data-id="${id}" data-field="kg" value="${esc(x.kg)}" placeholder="0"></label><label>Ripetizioni / tempo per serie<input data-id="${id}" data-field="reps" value="${esc(x.reps)}" maxlength="160" placeholder="Es. 12 / 11 / 10"></label></div><div class="previous">${esc(previous(id))}</div></details></article>`;}
function workout(){const d=DAYS[state.day],p=phase();return `<div class="row"><div><span class="eyebrow">IL TUO ALLENAMENTO</span><h1>Un giorno alla volta.</h1></div>${weekSelector()}</div><div class="days" aria-label="Giorno di allenamento">${DAYS.map((x,i)=>`<button data-day="${i}" class="${state.day===i?'selected':''}" aria-pressed="${state.day===i}">${x.short}</button>`).join('')}</div><section class="session">${d.image?`<img class="session-image" src="images/piano-${d.image}.jpg" alt="Immagine illustrativa della sessione, dal PDF">`:''}<span class="eyebrow">${d.name} · ${p.title}</span><h1>${d.title}</h1><p>${d.intro}</p><div class="row"><small id="done-text"></small><small>${completed(state.week)} / 5 sessioni</small></div><div class="progress-track" role="progressbar" aria-label="Esercizi completati" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span id="done-bar"></span></div></section>${state.week>4?`<div class="notice"><strong>Settimana ${state.week} · ${p.title}</strong><br>${p.text}<br>Le dosi sotto sono quelle delle singole schede originali: il PDF non chiarisce tutte le eccezioni alla progressione. Registra le serie effettive, senza aumenti automatici.</div>`:''}${state.day<5?`<details class="card"><summary>Prima di iniziare · blocco posturale 8 min</summary><p class="muted">Spunte separate per ciascun giorno e settimana.</p>${POSTURE.map((e,i)=>card(e,i,'p')).join('')}</details>`:''}<section aria-label="Esercizi della sessione">${d.ex.map((e,i)=>card(e,i,'e')).join('')}</section>${state.day===4?`<div class="card row"><div><h3>Giri del circuito</h3><span id="round-label">${session().rounds||0} / ${state.week>8?5:'4–5'}</span></div><div class="actions"><button id="round-minus" aria-label="Togli un giro">−</button><button id="round-plus">Giro fatto +</button></div></div>`:''}<div class="row"><button id="complete" class="primary">${session().completed?'Segna come non completata':'Concludi sessione'}</button><span class="muted subtle">${session().completed?'Sessione completata ✓':'Spunta e registra al tuo ritmo.'}</span></div><p class="source-note">Fonte: il tuo PDF. Le fotografie sono illustrative, non una guida alla tecnica. <a href="piano-originale.pdf" target="_blank" rel="noopener">Apri il piano originale</a>.</p>`;}
function chart(){const entries=state.diary.filter(x=>Number.isFinite(x.weight)&&x.weight>0).sort((a,b)=>a.date.localeCompare(b.date));if(entries.length<2)return '<p class="muted">Registra almeno due pesate per vedere l’andamento.</p>';const v=entries.map(x=>x.weight),min=Math.min(...v)-.5,max=Math.max(...v)+.5;const points=v.map((n,i)=>[45+i*480/(v.length-1),150-(n-min)*115/(max-min)]);return `<svg class="chart" viewBox="0 0 560 185" role="img" aria-label="Peso: da ${v[0]} a ${v[v.length-1]} kg, ${v.length} rilevazioni"><line x1="45" y1="155" x2="525" y2="155" stroke="#cad7e3"/><polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#168560" stroke-width="3"/>${points.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="4" fill="#168560"/>`).join('')}<text x="45" y="180" font-size="14" fill="#52677c">${esc(entries[0].date)}</text><text x="525" y="180" text-anchor="end" font-size="14" fill="#52677c">${esc(entries.at(-1).date)}</text><text x="45" y="20" font-size="14" fill="#52677c">${Math.min(...v)}–${Math.max(...v)} kg</text></svg>`;}
function progress(){const total=Array.from({length:12},(_,i)=>completed(i+1)).reduce((a,b)=>a+b,0);return `<div class="row"><div><span class="eyebrow">IL PERCORSO</span><h1>Piccoli progressi, visibili.</h1></div>${weekSelector()}</div><div class="grid"><div class="card"><span class="eyebrow">SESSIONI COMPLETATE</span><span class="metric">${total}<small> / 60</small></span></div><div class="card"><span class="eyebrow">FASE ATTUALE</span><h2>${phase().title}</h2><small>Settimane ${phase().weeks}</small></div></div><div class="weeks">${Array.from({length:12},(_,i)=>`<button data-week="${i+1}" class="${state.week===i+1?'current':''}">${i+1}<small>${completed(i+1)}/5</small></button>`).join('')}</div><div class="card"><h2>${phase().title}</h2><p>${phase().text}</p><small>Indicazioni del PDF, non aumenti obbligatori. Le prestazioni e il peso non garantiscono un aumento equivalente di massa muscolare.</small></div>${state.week===6?'<div class="notice">Il PDF ricorda un controllo del colesterolo alla settimana 6: concorda tempi e valutazione con il medico.</div>':''}<div class="card"><h2>Andamento del peso</h2>${chart()}</div><form id="diary-form" class="card"><h2>Il tuo diario · settimana ${state.week}</h2><div class="grid"><label>Data<input name="date" type="date" required value="${localDate()}"></label><label>Peso (kg)<input name="weight" type="number" step="0.1" min="1" max="500" inputmode="decimal"></label><label>Vita (cm)<input name="waist" type="number" step="0.1" min="1" max="300" inputmode="decimal"></label><label>Petto (cm)<input name="chest" type="number" step="0.1" min="1" max="300" inputmode="decimal"></label></div><label style="margin-top:16px">Note / come mi sento<textarea name="notes" maxlength="2000" placeholder="Energia, fatica, carichi, sensazioni…"></textarea></label><button class="primary" type="submit" style="margin-top:16px">Salva nel diario</button></form><div class="card"><h2>Le tue registrazioni</h2>${state.diary.length?state.diary.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="log"><div class="row"><strong>${esc(x.date)} · sett. ${x.week}</strong><button data-delete="${esc(x.id)}" class="subtle">Elimina</button></div><p>${x.weight?esc(x.weight)+' kg · ':''}${x.waist?'Vita '+esc(x.waist)+' cm · ':''}${x.chest?'Petto '+esc(x.chest)+' cm':''}</p><p>${esc(x.notes)}</p></article>`).join(''):'<p class="muted">Nessuna registrazione. Parti da come stai oggi.</p>'}</div>`;}
function nutrition(){return `<span class="eyebrow">DAL TUO PIANO</span><h1>Nutrizione quotidiana.</h1><div class="notice">Schema alimentare trascritto dal PDF, non validato come dieta personalizzata. Il documento indica circa 2.900–3.000 kcal al giorno: l’app non calcola né verifica questo fabbisogno. Per il colesterolo e le porzioni, confrontati con medico o dietista.</div>${MEALS.map((m,i)=>`<div class="card"><span class="eyebrow">0${i+1}</span><h2>${m[0]}</h2><p>${m[1]}</p></div>`).join('')}<div class="card"><h2>Note del documento</h2><p>Il PDF propone proteine a ogni pasto, circa 2 litri d’acqua al giorno e una pesata settimanale nelle stesse condizioni. Sono indicazioni del documento, non obiettivi calcolati dall’app.</p><p>Il pane a lunga lievitazione non equivale a pane senza lievito. La variazione di peso non misura da sola la massa muscolare.</p><a href="piano-originale.pdf" target="_blank" rel="noopener">Consulta tutte le indicazioni originali</a></div>`;}
function shopping(){return `<div class="row"><div><span class="eyebrow">LA TUA LISTA</span><h1>Spesa, senza fogli.</h1></div>${weekSelector()}</div><p class="muted">Lista del PDF, con spunte indipendenti per ogni settimana.</p>${SHOP.map((group,g)=>`<section class="card shopping"><h2>${group[0]}</h2>${group[1].map((x,i)=>{const k=state.week+'-'+g+'-'+i;return `<label class="check"><input type="checkbox" data-shop="${k}" ${state.shop[k]?'checked':''}><span>${x}</span></label>`;}).join('')}</section>`).join('')}<button id="clear-shop">Togli le spunte di questa settimana</button>`;}
function settings(){return `<span class="eyebrow">IL TUO SPAZIO</span><h1>Dati e installazione.</h1><div class="card"><h2>Mettila sulla Home dell’iPhone</h2><p>Quando l’app è pubblicata su un indirizzo HTTPS, aprila in Safari, premi Condividi e scegli <strong>Aggiungi alla schermata Home</strong>.</p><p>Lo ZIP non è installabile direttamente dall’app File: prima serve ospitare la cartella su un server. Puoi usare anche il tuo NUC, configurando HTTPS.</p></div><div class="card"><h2>I dati restano qui</h2><p>Salvataggio sul browser/dispositivo usato, senza sincronizzazione cloud. Cancellare i dati del browser, cambiare indirizzo o usare la navigazione privata può far perdere lo storico. Esporta un backup regolarmente.</p><p class="${storageOK?'muted':'warning'}">${storageOK?'Salvataggio locale disponibile.':'Salvataggio locale non disponibile. Esporta prima di chiudere.'}</p><div class="actions"><button id="export" class="primary">Esporta backup JSON</button><button id="export-csv">Esporta diario CSV</button></div><details><summary>Ripristina un backup</summary><p>Il ripristino sostituisce i dati attuali, dopo conferma.</p><label>File JSON esportato dall’app<input id="import" type="file" accept="application/json,.json"></label></details></div><div class="card"><h2>Come usare il piano</h2><p>Seleziona manualmente la settimana 1–12 e il giorno. Ogni scheda conserva spunte, pesi e ripetizioni. Quando torni sullo stesso esercizio nelle settimane successive, trovi l’ultima registrazione precedente.</p><p>Il timer usa l’orario reale e recupera il tempo trascorso quando riapri l’app. Su iPhone, con schermo bloccato o app in background, il suono non è garantito. Non ci sono notifiche push.</p><p>Le schede mantengono le dosi base del PDF; le indicazioni di progressione sono separate per non applicare automaticamente aumenti non chiariti dal documento.</p></div><div class="notice">Questo piano è generale e non sostituisce una valutazione professionale. Le promesse di aumento muscolare o correzione della postura del PDF non sono garanzie dell’app. Il piano fa riferimento a mal di schiena e colesterolo: verifica l’idoneità del programma con un professionista.</div><a href="piano-originale.pdf" target="_blank" rel="noopener">Apri PDF originale · 11 pagine</a>`;}
function render(){document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});$('#main').innerHTML=({allenamento:workout,progressi:progress,nutrizione:nutrition,spesa:shopping,impostazioni:settings})[view]();if(view==='allenamento')updateProgress();}
function updateProgress(){const ids=[...DAYS[state.day].ex.map((_,i)=>'e'+i),...(state.day<5?POSTURE.map((_,i)=>'p'+i):[])];const done=ids.filter(k=>item(k).done).length,p=Math.round(done/ids.length*100);$('#done-text').textContent=done+' / '+ids.length+' esercizi spuntati';$('#done-bar').style.width=p+'%';$('.session [role=progressbar]').setAttribute('aria-valuenow',p);}
function navigate(v){if(!['allenamento','progressi','nutrizione','spesa','impostazioni'].includes(v))return;view=v;location.hash=v;render();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view){navigate(b.dataset.view);return;}
 if(b.dataset.day!==undefined){state.day=Number(b.dataset.day);save();render();return;}
 if(b.dataset.week){state.week=Number(b.dataset.week);save();render();return;}
 if(b.id==='complete'){const s=mutableSession();if(!s.completed&&!confirm('Marcare questa sessione come completata? Le spunte e i valori inseriti non cambiano.'))return;s.completed=!s.completed;save();render();return;}
 if(b.id==='round-plus'||b.id==='round-minus'){const s=mutableSession();s.rounds=Math.max(0,Math.min(5,(s.rounds||0)+(b.id==='round-plus'?1:-1)));save();$('#round-label').textContent=s.rounds+' / '+(state.week>8?'5':'4–5');return;}
 if(b.dataset.delete){if(confirm('Eliminare questa registrazione dal diario?')){state.diary=state.diary.filter(x=>x.id!==b.dataset.delete);save();render();}return;}
 if(b.id==='clear-shop'){if(confirm('Togliere tutte le spunte della settimana '+state.week+'?')){Object.keys(state.shop).filter(k=>k.startsWith(state.week+'-')).forEach(k=>delete state.shop[k]);save();render();}return;}
 if(b.id==='export')download(JSON.stringify(state,null,2),'inverno-backup-'+localDate()+'.json','application/json');
 if(b.id==='export-csv'){const safe=x=>'"'+String(x??'').replace(/^[=+\-@]/,"'$&").replace(/"/g,'""')+'"';const rows=[['Data','Settimana','Peso kg','Vita cm','Petto cm','Note'],...state.diary.map(x=>[x.date,x.week,x.weight,x.waist,x.chest,x.notes])];download('\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n'),'inverno-diario.csv','text/csv;charset=utf-8');}
});
document.addEventListener('change',async e=>{const t=e.target;
 if(t.id==='week'){state.week=Number(t.value);save();render();}
 if(t.dataset.check){const s=mutableSession(),id=t.dataset.check;s.items[id]={...item(id),done:t.checked};save();t.closest('[data-card]').classList.toggle('done',t.checked);updateProgress();}
 if(t.dataset.shop){state.shop[t.dataset.shop]=t.checked;save();}
 if(t.id==='import'&&t.files[0]){try{if(t.files[0].size>5e6)throw Error();const data=JSON.parse(await t.files[0].text());if(!validState(data))throw Error();if(confirm('Sostituire tutti i dati locali con questo backup?')){state=data;storageOK=true;const ok=save();render();notify(ok?'Backup ripristinato.':'Backup caricato, ma non salvato: esportalo prima di chiudere.');}}catch{notify('Backup non valido. Nessun dato è stato cambiato.');}t.value='';}
});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.field){const s=mutableSession(),id=t.dataset.id;s.items[id]={...item(id),[t.dataset.field]:t.value};save();}});
document.addEventListener('submit',e=>{if(e.target.id!=='diary-form')return;e.preventDefault();const f=new FormData(e.target);if(!f.get('weight')&&!f.get('waist')&&!f.get('chest')&&!String(f.get('notes')).trim()){notify('Inserisci almeno una misura o una nota.');return;}const n=k=>f.get(k)===''?'':Number(f.get(k));state.diary.push({id:globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random(),week:state.week,date:f.get('date'),weight:n('weight'),waist:n('waist'),chest:n('chest'),notes:String(f.get('notes'))});const ok=save();render();if(ok)notify('Registrazione salvata.');});
function download(data,name,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
let timer={left:60,deadline:0,running:false},audioContext;
try{const t=JSON.parse(sessionStorage.getItem(KEY+'-timer'));if(t&&Number.isFinite(t.left)&&Number.isFinite(t.deadline)&&typeof t.running==='boolean')timer=t;}catch{}
function persistTimer(){try{sessionStorage.setItem(KEY+'-timer',JSON.stringify(timer));}catch{}}
function tick(){if(timer.running){timer.left=Math.max(0,Math.ceil((timer.deadline-Date.now())/1000));if(timer.left===0){timer.running=false;persistTimer();notify('Recupero terminato.');try{const o=audioContext.createOscillator();o.connect(audioContext.destination);o.frequency.value=660;o.start();o.stop(audioContext.currentTime+.25);}catch{}}}$('#clock').textContent=String(Math.floor(timer.left/60)).padStart(2,'0')+':'+String(timer.left%60).padStart(2,'0');$('#timer-toggle').textContent=timer.running?'Pausa':(timer.left===0?'Riparti':'Avvia');}
$('#timer-toggle').onclick=()=>{try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}if(timer.running){tick();timer.running=false;}else{if(timer.left<=0)timer.left=Number($('#duration').value);timer.deadline=Date.now()+timer.left*1000;timer.running=true;}persistTimer();tick();};
function resetTimer(){timer={left:Number($('#duration').value),deadline:0,running:false};persistTimer();tick();}
$('#timer-reset').onclick=resetTimer;$('#duration').onchange=resetTimer;setInterval(tick,250);document.addEventListener('visibilitychange',tick);
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['allenamento','progressi','nutrizione','spesa','impostazioni'].includes(v)){view=v;render();}});
if(['allenamento','progressi','nutrizione','spesa','impostazioni'].includes(location.hash.slice(1)))view=location.hash.slice(1);
render();tick();if(!storageOK)notify('Dati locali non leggibili: nessun dato precedente è stato sovrascritto.');
if('serviceWorker' in navigator&&['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_training_week',description:'Legge le sessioni completate della settimana selezionata, senza modificare i dati.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input&&Object.keys(input).length)throw new Error('Nessun parametro previsto');return {week:state.week,completed:completed(state.week),phase:phase().title};}})).catch(()=>{});}catch{}}

// V3: estensione compatibile con dati e backup V2.
let focusIndex=null;
const baseUpdateProgress=updateProgress;
updateProgress=function(){if($('#done-text'))baseUpdateProgress();};
const baseCard=card,baseWorkout=workout,baseRender=render;
function seriesCount(id){if(id.startsWith('p'))return 1;const index=Number(id.slice(1));if(state.day===4)return index===4?1:4;if(state.day===5)return 1;const dose=DAYS[state.day].ex[index][1];const match=dose.match(/^(\d+)\s*×/);return match?Number(match[1]):1;}
function getSets(id){const x=item(id);return Array.isArray(x.sets)?x.sets:Array.from({length:seriesCount(id)},()=>({kg:'',reps:'',done:false}));}
function priorSets(id){for(let w=state.week-1;w>0;w--){const x=session(w).items[id];if(Array.isArray(x?.sets)&&x.sets.some(s=>s.kg||s.reps))return {week:w,sets:x.sets};}return null;}
function seriesHTML(id){const sets=getSets(id),prior=priorSets(id),e=id.startsWith('p')?POSTURE[Number(id.slice(1))]:DAYS[state.day].ex[Number(id.slice(1))],timed=/sec|min/.test(e[1]);return `<div class="series-panel"><div class="series-heading"><span>REGISTRO SERIE</span><span>${timed?'Tempo libero: es. 40 sec':'Ripetizioni per serie'}</span></div><div class="set-labels"><span>Serie</span><span>Kg</span><span>${timed?'Tempo':'Rip.'}</span><span>Fatta</span></div>${sets.map((s,i)=>`<div class="set-row ${s.done?'set-done':''}"><span class="set-number">${i+1}</span><input aria-label="${esc(e[0])}, serie ${i+1}, kg" type="number" min="0" max="999" step="0.25" inputmode="decimal" data-set-id="${id}" data-set-index="${i}" data-set-field="kg" value="${esc(s.kg)}" placeholder="${esc(prior?.sets[i]?.kg||'—')}"><input aria-label="${esc(e[0])}, serie ${i+1}, ${timed?'tempo':'ripetizioni'}" ${timed?'':'inputmode="numeric"'} maxlength="30" data-set-id="${id}" data-set-index="${i}" data-set-field="reps" value="${esc(s.reps)}" placeholder="${esc(prior?.sets[i]?.reps||'—')}"><button class="set-check" data-set-toggle="${id}" data-set-index="${i}" aria-pressed="${!!s.done}" aria-label="${s.done?'Annulla':'Completa'} serie ${i+1}">${s.done?'✓':'○'}</button></div>`).join('')}<div class="series-footer"><button data-add-set="${id}">+ Serie</button>${sets.length>1?`<button data-remove-set="${id}">− Ultima</button>`:''}<small>${prior?'Ultimo registro: settimana '+prior.week+'. Valori suggeriti nei campi vuoti.':'Nessuna serie precedente registrata.'}</small></div></div>`;}
card=function(e,i,prefix){const id=prefix+i;return baseCard(e,i,prefix).replace('<details>',`<button class="guide-open" data-guide="${esc(e[0])}"><span aria-hidden="true">▶</span> Come si fa</button><details>`).replace('</article>',seriesHTML(id)+'</article>');};
workout=function(){
 const doneWeek=completed(state.week),base=baseWorkout();
 const weekly=`<section class="weekly-summary" aria-label="Avanzamento della settimana"><div class="weekly-summary-head"><strong>Questa settimana</strong><span>${doneWeek} / 5</span></div><div class="weekly-summary-track" role="progressbar" aria-label="Sessioni completate nella settimana" aria-valuemin="0" aria-valuemax="5" aria-valuenow="${doneWeek}"><span style="width:${doneWeek*20}%"></span></div><small>${doneWeek===5?'Settimana completata. Ottimo lavoro!':'Ancora '+(5-doneWeek)+' '+(5-doneWeek===1?'sessione':'sessioni')+' per completarla.'}</small></section>`;
 return base
  .replace('</div><section class="session">','</div>'+weekly+'<section class="session">')
  .replace('<section aria-label="Esercizi della sessione">',`<div class="training-controls"><div><span class="eyebrow">MODALITÀ ALLENAMENTO</span><h2>Concentrati sulla prossima serie.</h2></div><button id="start-focus" class="primary">Inizia allenamento →</button><label class="check"><input id="auto-rest" type="checkbox" ${state.autoRest!==false?'checked':''}>Recupero automatico dopo la serie</label></div><section aria-label="Esercizi della sessione">`);
};
function focused(){const exercises=DAYS[state.day].ex;focusIndex=Math.max(0,Math.min(exercises.length-1,focusIndex));return `<div class="focus-top row"><button id="exit-focus">← Scheda completa</button><span class="pill">${DAYS[state.day].short} · settimana ${state.week}</span></div><div class="focus-title"><span class="eyebrow">ESERCIZIO ${focusIndex+1} DI ${exercises.length}</span><h1>${esc(exercises[focusIndex][0])}</h1><p>${esc(exercises[focusIndex][2])}</p></div>${card(exercises[focusIndex],focusIndex,'e')}<div class="focus-navigation"><button id="focus-prev" ${focusIndex===0?'disabled':''}>← Precedente</button><button id="focus-next" class="primary">${focusIndex===exercises.length-1?'Torna al riepilogo':'Successivo →'}</button></div><p class="source-note">Le spunte e le serie si salvano subito. Per concludere la sessione usa il riepilogo. Il blocco posturale è nella scheda completa.</p>`;}
function guideVideo(title){return GUIDE_VIDEOS[title]||'https://www.youtube.com/results?search_query='+encodeURIComponent(title+' esecuzione corretta Project inVictus');}
function openGuide(title){const g=GUIDES[title];if(!g){notify('Guida non disponibile per questo esercizio.');return;}const direct=!!GUIDE_VIDEOS[title];$('#guide-content').innerHTML=`<div class="guide-number">GUIDA ESERCIZIO</div><h1>${esc(title)}</h1><ol class="guide-steps">${g[0].map((x,i)=>`<li><span>${i+1}</span><p>${esc(x)}</p></li>`).join('')}</ol><div class="guide-cues"><div><span>RESPIRAZIONE</span><p>${esc(g[1])}</p></div><div class="guide-error"><span>EVITA</span><p>${esc(g[2])}</p></div><div><span>VERSIONE PIÙ FACILE</span><p>${esc(g[3])}</p></div></div><a class="video-link" href="${guideVideo(title)}" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">▶</span> ${direct?'Apri video selezionato':'Cerca una dimostrazione video'}</a><p class="guide-note">Guarda la dimostrazione prima di iniziare e prova il movimento senza peso. Se senti dolore, interrompi.</p>`;const d=$('#guide-dialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');}
render=function(){baseRender();if(view==='allenamento'&&focusIndex!==null)$('#main').innerHTML=focused();else if(view!=='allenamento')focusIndex=null;};
function startAutoRest(){if(state.autoRest===false)return;const seconds=DAYS[state.day].rest;$('#duration').value=String(seconds);timer={left:seconds,deadline:Date.now()+seconds*1000,running:true};try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}persistTimer();tick();}
function setRowDone(id,index){const sets=getSets(id).map(s=>({...s}));if(!sets[index])return;sets[index].done=!sets[index].done;mutableSession().items[id]={...item(id),sets,done:sets.every(s=>s.done)};save();if(sets[index].done)startAutoRest();render();}
document.addEventListener('input',e=>{const t=e.target;if(!t.dataset.setField)return;const id=t.dataset.setId,index=Number(t.dataset.setIndex),sets=getSets(id).map(s=>({...s}));if(!sets[index])return;sets[index][t.dataset.setField]=t.value;mutableSession().items[id]={...item(id),sets};save();});
document.addEventListener('change',e=>{if(e.target.id==='auto-rest'){state.autoRest=e.target.checked;save();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.id==='start-focus'){focusIndex=0;render();window.scrollTo(0,0);}
 if(b.id==='exit-focus'){focusIndex=null;render();}
 if(b.id==='focus-prev'){focusIndex=Math.max(0,focusIndex-1);render();window.scrollTo(0,0);}
 if(b.id==='focus-next'){focusIndex=focusIndex===DAYS[state.day].ex.length-1?null:focusIndex+1;render();window.scrollTo(0,0);}
 if(b.dataset.guide)openGuide(b.dataset.guide);
 if(b.id==='guide-close'){const d=$('#guide-dialog');if(typeof d.close==='function')d.close();else d.removeAttribute('open');}
 if(b.dataset.setToggle)setRowDone(b.dataset.setToggle,Number(b.dataset.setIndex));
 if(b.dataset.addSet){const id=b.dataset.addSet,sets=getSets(id).map(s=>({...s}));if(sets.length>=12){notify('Massimo 12 serie per esercizio.');return;}sets.push({kg:'',reps:'',done:false});mutableSession().items[id]={...item(id),sets,done:false};save();render();}
 if(b.dataset.removeSet){const id=b.dataset.removeSet,sets=getSets(id).map(s=>({...s}));if(sets.length<=1)return;const last=sets.at(-1);if((last.done||last.kg||last.reps)&&!confirm('Eliminare l’ultima serie e i suoi valori?'))return;sets.pop();mutableSession().items[id]={...item(id),sets,done:sets.every(s=>s.done)};save();render();}
});
if(!$('#guide-dialog')){const d=document.createElement('dialog');d.id='guide-dialog';d.className='guide-dialog';d.innerHTML='<div class="guide-dialog-head"><span>INVERNO · TECNICA</span><button id="guide-close" aria-label="Chiudi guida">×</button></div><div id="guide-content"></div>';document.body.append(d);d.addEventListener('click',e=>{if(e.target===d){if(typeof d.close==='function')d.close();else d.removeAttribute('open');}});}
render();

// V5.1: idratazione giornaliera, compatibile con i backup precedenti.
const baseProgressHydration=progress;
function waterTarget(){return Number.isFinite(state.hydrationTarget)?Math.max(500,Math.min(6000,state.hydrationTarget)):2000;}
function waterAmount(date=localDate()){const value=state.hydration?.[date];return Number.isFinite(value)?Math.max(0,value):0;}
function setWater(value,date=localDate()){state.hydration??={};state.hydration[date]=Math.max(0,Math.min(10000,Math.round(value/50)*50));}
function waterCard(){
 const amount=waterAmount(),target=waterTarget(),percent=Math.min(100,Math.round(amount/target*100)),bottles=(amount/2000).toLocaleString('it-IT',{maximumFractionDigits:2});
 return `<section class="water-card" aria-labelledby="water-title"><div class="water-copy"><span class="eyebrow">IDRATAZIONE · OGGI</span><h2 id="water-title">La tua borraccia da 2 litri</h2><p><strong>${amount.toLocaleString('it-IT')} ml</strong> di ${target.toLocaleString('it-IT')} ml · ${percent}%</p><div class="water-track" role="progressbar" aria-label="Acqua bevuta oggi" aria-valuemin="0" aria-valuemax="${target}" aria-valuenow="${amount}"><span style="width:${percent}%"></span></div><small>${amount>=target?'Obiettivo raggiunto ✓':Math.max(0,target-amount).toLocaleString('it-IT')+' ml ancora da bere'} · ${bottles} borracce</small><div class="water-actions"><button data-water-add="-250">− 250 ml</button><button data-water-add="250">+ 250 ml</button><button data-water-add="500">+ 500 ml</button><button data-water-add="2000" class="primary">+ Borraccia</button></div><label class="water-target">Obiettivo giornaliero (ml)<input id="water-target" type="number" inputmode="numeric" min="500" max="6000" step="250" value="${target}"></label></div><div class="water-bottle" aria-hidden="true"><div class="water-fill" style="height:${percent}%"></div><span>2 L</span></div></section>`;
}
progress=function(){return baseProgressHydration().replace('<div class="grid">',waterCard()+'<div class="grid">');};
document.addEventListener('click',e=>{
 const button=e.target.closest('[data-water-add]');if(!button)return;
 setWater(waterAmount()+Number(button.dataset.waterAdd));save();render();
});
document.addEventListener('change',e=>{
 if(e.target.id!=='water-target')return;
 const target=Math.max(500,Math.min(6000,Number(e.target.value)||2000));state.hydrationTarget=Math.round(target/250)*250;save();render();
});
render();

// Un aggiornamento viene applicato solo dopo un gesto dell’utente.
if('serviceWorker' in navigator){navigator.serviceWorker.ready.then(reg=>{const offer=()=>{if(!reg.waiting)return;const banner=document.createElement('div');banner.className='update-banner';banner.innerHTML='<span>È disponibile una nuova versione.</span><button>Aggiorna app</button>';banner.querySelector('button').onclick=()=>{if(!save())return;reg.waiting?.postMessage('ACTIVATE_UPDATE');};document.body.append(banner);};offer();reg.addEventListener('updatefound',()=>{const installing=reg.installing;installing?.addEventListener('statechange',()=>{if(installing.state==='installed')offer();});});}).catch(()=>{});let reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloaded){reloaded=true;location.reload();}});}
